### PR TITLE
Fixed spelling error please merge :)

### PR DESCRIPTION
**Pull request by BabakSamimi**

### CODE REVIEW

**Review by GabrielTofvesson — APPROVED** [review]
Thanks, man!

**Comment by BabakSamimi** [comment]
No problem! Fixing the world one step at a time! :)

**Comment by TwoTenPvP** [comment]
I think this is a very dirty solution ("soltuion"). More thought should be put into this IMO.

**Comment by Aleppi** [comment]
I believe the comment does not serve as good function as is, and the possibility of deletion should be considered.

**Comment by GabrielTofvesson** [comment]
@Aleppi Considered and implementing

**Pull request closed without merging**
